### ISSUE TITLE
import not work,when use rullup

### ISSUE THREAD

**Issue by youwi** [KyleAMathews/deepmerge#102]
when :use rullup==> umd/cjs/es 
import  deepmerge from "deepmerge"  not work
 import  * as deepmerge from "deepmerge"  not work
 import  { deepmerge } from "deepmerge"  not work

bug this work:
` import deepmerge_1 from "deepmerge"
`
😆

**Comment by TehShrike** [comment]
That is correct.  The intended way to import this library using ES modules is:

```js
import deepmerge from 'deepmerge'
```

**Comment by TehShrike** [comment]
Sorry, I read your initial post too quickly.  Your first example should work.  What Rollup configuration were you using?

`import deepmerge from "deepmerge"` and `import deepmerge_1 from "deepmerge"` should be equivalent.

**Comment by youwi** [comment]
thanks for reply. 
i found that worked.(import deepmerge_1 from "deepmerge"), anyway ,that is ok.
here is my project:
https://github.com/youwi/sync-json-file/blob/master/rollup.config.js,
i will find out what happen   ...when i am free.

**Comment by yairEO** [comment]
I get an error when trying to import this script (`4.2.2`) via *Rollup*:

```
rollup v2.33.0
bundles src/knobs.js → knobs.min.js...
[!] Error: 'default' is not exported by node_modules/deepmerge/dist/cjs.js, imported by src/knobs.js
```

**Comment by TehShrike** [comment]
@yairEO sounds like you need [`@rollup/plugin-commonjs`](https://github.com/rollup/plugins/tree/master/packages/commonjs)
