### ISSUE TITLE
Default option for arrayOverwrite

### ISSUE THREAD

**Issue by mesqueeb** [KyleAMathews/deepmerge#113]
The current method to overwrite arrays is:
```js
const overwriteMerge = (destinationArray, sourceArray, options) => sourceArray
merge(
	{a: [1, 2, 3]},
	{a: [3, 2, 1]},
	{ arrayMerge: overwriteMerge }
)
```
Everywhere I want to use this overwrite array option (which is a lot of places) I would have to define `overwriteMerge` or import it...

I would love standard compatibility with a syntax similar to:
```js
merge(
	{a: [1, 2, 3]},
	{a: [3, 2, 1]}
	{ arrayMerge: 'overwrite' }
)
```
Just a humble request.
Best regards!

**Comment by TehShrike** [comment]
You want to make a `merge.js` file in your `shared` directory that exposes deepmerge with whatever defaults you want - see https://github.com/KyleAMathews/deepmerge/issues/111#issuecomment-395134828
