### ISSUE TITLE
[Bug] Falls into endless loop with Firebase user object.

### ISSUE THREAD

**Issue by mesqueeb** [KyleAMathews/deepmerge#115]
Deepmerge fails to merge two [Firebase user objects](https://firebase.google.com/docs/reference/js/firebase.User).

<img width="342" alt="image" src="https://user-images.githubusercontent.com/3253920/43352513-98d9ffa2-925f-11e8-82a2-14ba2509cf63.png">

**Comment by mesqueeb** [comment]
If you have never worked with Firebase before, it might be annoying for you to reproduce and debug. Also it's difficult for me to make an easy to reproduce setup because you need to be authenticated through firebase...

I'm so sorry!
I'd love the library to detect a Firebase user object and just overwrite the entire thing.

The way it's integrated into my app now is I'm merging all kind of things, but only the Firebase user object bugs. I have no way to let deepmerge know when it's merging the firebase user object without going through some rather untrivial changes. So i'd be great if `deepmerge` could detect this on its own.

Do you know what makes it special or different from other JS objects? Thakns!

**Comment by TehShrike** [comment]
I'm going to guess that the objects have cycles, like

```js
const root = {}
root.child = {
  parent: root
}
```

deepmerge doesn't have any code to detect/avoid cycles.

You could pass in a custom [`isMergeableObject`](https://github.com/KyleAMathews/deepmerge#ismergeableobject) that would return false for any objects seen before, that would probably do the trick.

**Comment by TehShrike** [comment]
You could also pass in a custom `isMergeableObject` to return false for Firebase objects.
