### ISSUE TITLE
Is there any way to keep the prototype of the first obj?

### ISSUE THREAD

**Issue by shijistar** [KyleAMathews/deepmerge#118]
```js
let result = deepmerge(animal, cat);
```
If I want the result keep the prototype of `animal` and keeps `result instanceof AnimalClass` is `true`, is there any way?

**Comment by TehShrike** [comment]
`deepmerge` focuses on cloning, not copying.

You can copy, though, if you set the [`clone` option](https://github.com/KyleAMathews/deepmerge#clone) to `false`.
