### ISSUE TITLE
unexpected behavior while merging on arrays 

### ISSUE THREAD

**Issue by rahulch** [KyleAMathews/deepmerge#12]
merge(["a1","a2","c1","f1","p1"],["t1","s1","c2","r1","p2","p3"])

>> ["a1", "a2", "c1", "f1", "p1", "p3", "s1", "c2", "r1", "p2"]

"t1" is missing in this list

**Comment by KyleAMathews** [comment]
@nrf110 is this published? Given that this module has ~200,000 downloads / month it'd be nice to get bug fixes out promptly :)

**Comment by nrf110** [comment]
still don't have access to publish this on npm, and don't do node enough to have time to maintain this anymore.  if anyone wants to volunteer to maintain, I can transfer ownership of the repo.

**Comment by KyleAMathews** [comment]
@nrf110 I'll maintain it.

**Comment by nhocki** [comment]
@KyleAMathews @nrf110 I also have time if you need an extra maintainer.

**Comment by KyleAMathews** [comment]
@nhocki @nrf110 the more the merrier! I'm a big fan of the OPEN open source model. As long as all work is done in pull requests and gets signed off by other maintainer(s) before merging, things should work smoothly with multiple maintainers.

https://github.com/rvagg/node-levelup/blob/master/CONTRIBUTING.md

**Comment by KyleAMathews** [comment]
@nrf110 thanks for transferring the repository. Have you had a chance to recover your NPM password so you can make me (us) owner there?

@nhocki I added you as a collaborator. Welcome!

**Comment by nrf110** [comment]
@KyleAMathews yes, just got it back this morning. If you send me your npm username I'll add you as an owner.

**Comment by TehShrike** [comment]
Fixed by 49cc4edcaba6749951d7f06f269e594d7bcafa22

**Comment by TehShrike** [comment]
(And published as 0.2.9 it looks like)
