### ISSUE TITLE
vue.js __ob__ (Observer) lost

### ISSUE THREAD

**Issue by patriciussanctus** [KyleAMathews/deepmerge#122]
analogue #76 
![2018-10-04 14 18 19](https://user-images.githubusercontent.com/16253399/46470740-62439c80-c7e0-11e8-865d-85a0bf693a4b.png)

need reproduction?
maybe it's must be controlled for performance? re `clone` option?
as expected ```{ clone: true }``` must repeat this behavior,
and ```{ clone: false }``` must save alias `__ob__`

**Comment by TehShrike** [comment]
deepmerge uses `Object.keys` to iterate over properties:

https://github.com/KyleAMathews/deepmerge/blob/master/index.js#L22

`Object.keys` only iterates over properties that are

- enumerable
- on the object directly, as opposed to somewhere up the prototype chain

I'm going to guess that `__ob__` doesn't meet one of those checks.

**Comment by TehShrike** [comment]
(You can use [`propertyIsEnumerable`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/propertyIsEnumerable) and [`hasOwnProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) to confirm)

**Comment by patriciussanctus** [comment]
@TehShrike 
```
__ob__.propertyIsEnumerable() => false
__ob__.hasOwnProperty() => false
```

**Comment by patriciussanctus** [comment]
internal structure of __ob__:
```
Observer {
  dep: Dep {
    id: 16650
    subs: [] // array with vue reactive dependences
  },
  value: {}, // alias to root
  vmCount: 0
}
```

**Comment by TehShrike** [comment]
The syntax is

```js
vueReactiveData.propertyIsEnumerable('__ob__')
vueReactiveData.hasOwnProperty('__ob__')
```

See the docs

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/propertyIsEnumerable
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty

**Comment by patriciussanctus** [comment]
oh 😛sorry)
propertyIsEnumerable('__ob__') => false
hasOwnProperty('__ob__') => true
