### ISSUE TITLE
Can I help maintain the module?

### ISSUE THREAD

**Issue by gr2m** [KyleAMathews/deepmerge#128]
We use `deepmerge` in [Octokit](https://github.com/octokit/rest.js) now and I can help maintain this module as part of my work on octokit. I don’t think there is lots to do anyway, but happy to help out. 

I maintain plenty of npm packages: https://www.npmjs.com/~gr2m. And I’m good at automating things, I’ve worked on https://greenkeeper.io/ and am co-maintainer of https://github.com/semantic-release/semantic-release

**Comment by TehShrike** [comment]
Sure thing, I'll add you as a contributor.

I tend towards [open open source](http://openopensource.org/).

Actually, @KyleAMathews it looks like I can't add contributors.  Do you want to fully transition the repo to me?

**Comment by TehShrike** [comment]
I will share the commit bit easily, but not the publish bit.  "open open source" does not imply giving access to publish to npm.

**Comment by KyleAMathews** [comment]
I added you @gr2m as a collaborator!

@TehShrike that sounds great — I think you need to delete your fork first though? GitHub errored when I tried transferring the repo to you because of your fork.

**Comment by TehShrike** [comment]
That makes sense.  I deleted my fork just now, should be good to try again.

**Comment by gr2m** [comment]
@KyleAMathews I accepted the invitation but got an "This invitation is invalid." error. I’ve never seen that before? Can you try again?

**Comment by gr2m** [comment]
I got the same error again, here is a screenshot for reference

https://github.com/octokit/rest.js/issues/620

Let me contact support and ask what’s going on

**Comment by gr2m** [comment]
I guess now @TehShrike has to invite me? Did you move the repo?

**Comment by TehShrike** [comment]
Github showed the invitation was still open, I dunno.

I cancelled that invite and re-invited you.

**Comment by gr2m** [comment]
that worked, cheers 👍
