### ISSUE TITLE
Arrays with similar items merge in an unexpected manner

### ISSUE THREAD

**Issue by basicallydan** [KyleAMathews/deepmerge#14]
Great library! I have a small issue with a certain behaviour though. Maybe it's on purpose.

```
var merge = require('../')
var x = { foo : { 'bar' : 3 }, ar : [ { thing : 'b' } ] }
var y = { foo : { 'baz' : 4 }, quux : 5, ar : [ { thing : 'a' } ] }
var merged = merge(x, y)
console.dir(merged)
```

I would expect `merged` to look like this:

```
{ foo: { bar: 3, baz: 4 }, ar: [ { thing : 'b' }, { thing: 'a' } ], quux: 5 }
```

However it looks like this:

```
{ foo: { bar: 3, baz: 4 }, ar: [ { thing: 'a' } ], quux: 5 }
```

To me the behaviour I expect makes more sense because an array is likely to be a set of similar objects with shared keys but different values for those keys. However, I understand if that is not one of the behaviours that you would expect with the library so I shall make my own fork, and if you agree with my expected behaviour, I'll do a pull request for it :smile:

**Comment by nhocki** [comment]
@basicallydan thanks for your fork, it worked for me. If you need a hand with the changes you proposed let me know, I can give you a hand.

**Comment by bdefore** [comment]
i was just surprised by this too. objects with the same name of type array i expected to concatenate and were replaced by the second one:

```
a =
  foo:
    bar: [
      {
        baz: "12"
      }
      {
        baz: "34"
      }
    ]
b =
  foo:
    bar: [
      {
        baz: "56"
      }
      {
        baz: "78"
      }
    ]
c = merge(a,b)

for item in c.foo.bar
  console.log 'item', item

# output:
# item { baz: '56' }
# item { baz: '78' }
```

**Comment by vyorkin** [comment]
I've just tried to use deepmerge to merge my env-specific webpack configs:
```
> baseConfig.module.loaders
[ { test: /\.css$/, exclude: /node_modules/, loader: 'css' } ]

> envConfig.module.loaders
[ { test: /\.jsx?$/,
    exclude: /node_modules/,
    loaders: [ 'react-hot', 'babel' ] } ]

> deepmerge(baseConfig, envConfig);
{ module: { loaders: [ [Object] ] }, debug: false, cache: true }
```

for me it was completely unexpected behaviour

**Comment by gyzerok** [comment]
Have the same issue here. Is there plans to resolve this or I need to create my own implementation?

**Comment by anthonator** [comment]
I don't think how array merges are currently implemented is incorrect. I also don't think concatenating arrays is incorrect behavior either. Both use cases are valid. That's why this is tricky.

What makes the most sense to me is to allow the user to decide how they want their arrays handled. Adding a third options parameter to `deepmerge` might be a viable option.

```js
var obj1 = { a: [{ b: 'c' }] }
var obj2 = { a: [{ d: 'e' }] }
deepmerge(obj1, obj2) // { a: [{ d: 'e' }] }
```

```js
var obj1 = { a: [{ b: 'c' }] }
var obj2 = { a: [{ d: 'e' }] }
deepmerge(obj1, obj2, { arrays: 'concat' }) // { a: [{ b: 'c' }, { d: 'e' }] }
```

**Comment by anthonator** [comment]
or this

https://github.com/KyleAMathews/deepmerge/pull/21

**Comment by vvo** [comment]
> What makes the most sense to me is to allow the user to decide how they want their arrays handled. Adding a third options parameter to deepmerge might be a viable option.

Yes lodash deepmerge does nothing about array by default but you can do it by providing a custom fn that check if it's an array: https://lodash.com/docs#merge

I think I was the one that did the "funny" array merge here, it really depends on your use case, that's why it's tricky as you said. Allowing an option and maybe reverting to the default that the first issue comment sayd would be better (+ major bump).

**Comment by vvo** [comment]
Anyone can do it here and propose the change

**Comment by vvo** [comment]
https://github.com/KyleAMathews/deepmerge/commit/9180a6d0116f3189ce7f71e3745bd6bbd48071b9

**Comment by anthonator** [comment]
Lodash has a deep extend extension called extendify that has a sane implementation of array merge strategies. Might make sense to check that out for inspiration.

**Comment by TehShrike** [comment]
Sounds like some folks already reached the same thought as I did in https://github.com/KyleAMathews/deepmerge/pull/32#issuecomment-249732353 - allowing consumers to pass in a custom array-merging function seems like a solid idea to me.

**Comment by TehShrike** [comment]
Looks like lots of folks had array merging issues.  They account for pull requests #20, #21, #22, #32

**Comment by TehShrike** [comment]
And issue #24!

**Comment by TehShrike** [comment]
I opened pull request #37 to solve this issue - comment there if you have any thoughts.
