### ISSUE TITLE
Bump to 1.0?

### ISSUE THREAD

**Issue by KyleAMathews** [KyleAMathews/deepmerge#15]
Looks like the library's API is pretty stable (once #12 and #14 are closed).

**Comment by iofjuupasli** [comment]
:+1:

**Comment by Kikobeats** [comment]
go ahead!

**Comment by TehShrike** [comment]
This is a widely-used library that has not changed in a while, and I don't intend to change it much going forward if I can help it.  I'll bump to 1.0 with my next publish.
