### ISSUE TITLE
Dates should merge

### ISSUE THREAD

**Issue by will123195** [KyleAMathews/deepmerge#31]
For example:
```sh
$ node
> require('deepmerge')({a:new Date()}, {a:new Date()})
{ a: {} }
```

Expected behavior:
```sh
$ node
> require('deepmerge')({a:new Date()}, {a:new Date()})
{ a: Mon Apr 11 2016 19:25:29 GMT-0400 (EDT) }
```

**Comment by neopostmodern** [comment]
You can fix this by changing [these lines](https://github.com/KyleAMathews/deepmerge/blob/master/index.js#L36) to:

```js
            if (Object.prototype.toString.call(src[key]).includes("Date")) {
                dst[key] = src[key];
            } else if (typeof src[key] !== 'object' || !src[key]) {
                dst[key] = src[key];
            }
            else {
                if (!target[key]) {
                    dst[key] = src[key];
                } else {
                    dst[key] = deepmerge(target[key], src[key]);
                }
            }
```

(I don't bother to write a PR because the package seems pretty abandoned.)

**Comment by KyleAMathews** [comment]
@neopostmodern this package isn't abandoned, it's waiting for someone like you to maintain it! ;-) Just sign up at https://github.com/KyleAMathews/deepmerge/issues/25 and I'll make you a collaborator + give you the release bit for NPM.
