### ISSUE TITLE
Why removing Bower ?

### ISSUE THREAD

**Issue by mistic100** [KyleAMathews/deepmerge#38]
Can you tell us why you removed the Bower file ? Luckily the package is still instable but as there is not more bower.json with the "main" definition, built tools cannot automatically inject the plugin without extra config.

Not everyone is using Webpack or such npm based tools.

**Comment by TehShrike** [comment]
Like I said at https://github.com/KyleAMathews/deepmerge/issues/25#issuecomment-249707744

I've never used bower, and I don't want to start using it just to maintain this package for another system.  Maintaining for Github and npm is enough for me.

**Comment by mistic100** [comment]
You don't need to be using Bower in order to publish.

Everything is already wired up and working (unlike NPM, publish are automatic when a tag is created).

Proof :
```
$ bower info deepmerge

Available versions:
  - 1.0.2
  - 1.0.1
  - 0.2.10
  - 0.2.9
  - 0.2.8
  - 0.2.5
  - 0.2.4
  - 0.2.1
  - 0.2.0
  - 0.1.0
  - 0.0.1
```

See ? The tags you created were registered.

You just have to leave the bower.json file and update the version.

Please don't block 50% of users :-)

**Comment by TehShrike** [comment]
Assuming that 50% of consumers are using bower seems wildly optimistic >_<

If bower uses Github tags, why does it need a version number in a bower.json file? :-x

I uses automated scripts to bump package.json version numbers, tag, and release.  Is there an automated command to bump the version in bower.json?

If I may ask, is there a reason you don't `npm install deepmerge` and then include `node_modules/deepmerge/index.js` in your scripts?

**Comment by mistic100** [comment]
> Assuming that 50% of consumers are using bower seems wildly optimistic >_<

I admit I have no idea, but there ar certainly as much NPM users than Bower users

> If bower uses Github tags, why does it need a version number in a bower.json file? :-x

Probably for the same reason a version is needed in package.json

> I uses automated scripts to bump package.json version numbers, tag, and release. Is there an automated command to bump the version in bower.json?

As there is no build-chain in the repo itself, I can't answer you. I use Grunt for my projects and grunt-bump updates the version for NPM, Bower and Composer

> If I may ask, is there a reason you don't npm install deepmerge and then include node_modules/deepmerge/index.js in your scripts?

Because I work with already existing build architecture that uses Wiredep to manage and and automatically include the dependencies, and it works on top of Bower.

**Comment by TehShrike** [comment]
It turns out bower doesn't need the version field in bower.json at all: https://github.com/bower/spec/blob/master/json.md#version

So, no problem then.  I'll replace the bower.json file without the version field for the next release.

**Comment by mistic100** [comment]
Oh, i didn't know, interesting (it makes a lot of sense actually :-) )

Thank you
