### ISSUE TITLE
Why would deepmerge assign 'undefined' attributes?

### ISSUE THREAD

**Issue by ivawzh** [KyleAMathews/deepmerge#53]
Currently `deepmerge` overwrites non-void attribute with `undefined` attribute:
```bash
$ node
const merge = require('./node_modules/deepmerge')
merge({ a: 'a' }, { a: undefined })
# Result: { a: undefined }
```

Why is this a desired behaviour? 

IMHO, the conventional `merge` method should skip `undefined` value. The popular libarary `Lodash` also aggrees that rule, see http://stackoverflow.com/a/33247597/1401634.

Would you please at least provide an option to turn this behaviour off?

Cheers

**Comment by TehShrike** [comment]
deepmerge operates on all properties of the input objects, no matter what their value is.

It may be that most people would assume the opposite - though I see that lodash's `assign` and `extend` behave the same way.

Making a breaking change for something fairly opinionated like this seems untenable.

I worry about feature creep, but I could see the argument for this.

I wouldn't be against a pull request adding a new `mergeUndefined` option.

We could also talk about a general solution - allowing users to pass in a `shouldOverwriteSource` function that would take the values from both objects, and determine if the merging object should be populated from the source object or the target object.  It would default to `() => true` for backwards compatibility.

Anyone have thoughts?

**Comment by macdja38** [comment]
I think if you can gather anything from the lodash example it's that both functionalities can be valuable. undefined is a possibly desirable value just like any other. I support addition of a custom function the user can define to dictate merge functionality, that said assuming the need for undefined is a common case I would also like to see a function that supports it out of the box.

**Comment by yvele** [comment]
Is there a workaround or and options not to merge `undefined` values?

**Comment by TehShrike** [comment]
Yeah, you can pass in a `customMerge` function: https://github.com/TehShrike/deepmerge#custommerge

Something like
```js
const customMerge = key => (a, b) => b === undefined ? a : deepmerge(a, b)
```

**Comment by yvele** [comment]
@TehShrike unfortunately your suggestion is not working as if 🤔
But once a robust solution has been found, I think I could be interesting to add it in the readme

**Comment by yuccai** [comment]
This should work :
```javascript
const customMerge = () => (a, b) => {
  const c = Object.keys(b)
    .filter([key, value] => value !== undefined) 
    .reduce((obj, [key, value]) => ({
      ...obj,
     key : value,
    });
  return deepmerge(a, c);
};
```

**Comment by psnehanshu** [comment]
`customMerge` never being called #199

**Comment by tran-simon** [comment]
@TehShrike Could this issue be reopened? We're having the same issue and the suggested solutions do not work
