### ISSUE TITLE
loading with requirejs cause error

### ISSUE THREAD

**Issue by tariqinaam** [KyleAMathews/deepmerge#58]
Trying to use html5-skin project (https://github.com/ooyala/html5-skin ) which has dependency of deepmerge. 
When loading html5-skin via requirejs, it causes `Mismatched` anonymous define() module: function ()`
Is there anything i need to do to use this library via requirejs... 
It works fine when loading wihtout requirejs..

**Comment by TehShrike** [comment]
What's spitting out the error message?  I'm not familiar with requirejs I'm not sure what would cause the issue.

Are there any more details in the error message?  Can you get requirejs to give you a more verbose error message?

*Duplicate https://github.com/ooyala/html5-skin/issues/730*

**Comment by TehShrike** [comment]
I'm guessing it has something to do with deepmerge using the UMD pattern so that the module works with the browser, CommonJS, and AMD.  But then it's getting bundled in a CommonJS environment in html5-skin, and then you try to load the whole thing from an AMD environment.

**Comment by TehShrike** [comment]
https://github.com/KyleAMathews/deepmerge/blob/master/index.js#L2-L8

**Comment by tariqinaam** [comment]
Yh, i think thats the issue. I have tried all possible way. but no luck.
I think the way it bundle, requirejs not able to see deepmerge and it throws error as deepmerge doesn't exist.

**Comment by TehShrike** [comment]
Maybe we should put the actual code in its own file, and bundle a "dist" version with the UMD pattern for publishing.

Then we could add `browser` and `module` fields to the package.json, pointing to the stand-alone file, so that bundlers would use it, and we could leave the `main` property pointing at the UMD version.

That way, bundlers wouldn't pull in the UMD pattern with the rest of the code.

Any thoughts?

**Comment by tariqinaam** [comment]
yes, we could give it a try.
I am a backend Dev and very little exp with FE, so can't really give my input on this. sorry.
can you plz suggest how to bundle this.

**Comment by TehShrike** [comment]
The bundler changes were published in 1.4.0.
