### ISSUE TITLE
Add a object-key merge option

### ISSUE THREAD

**Issue by jzimmek** [KyleAMathews/deepmerge#61]
Hi,

deepmerge solves lots of my requirements, but the following is not possible right now:

```
var x = {
  foo__1: { bar: 3 },
}

var y = {
  foo__2: { baz: 4 },
}

var expected = {
  foo: {
    bar: 3,
    baz: 4
  },
}

merge(x, y) // => expected
```

I cannot change the shape of "x" and "y". The keys needs to be transformed before the actual merge process. In the example above the transformation would look like this:

```
(key) => key.split("__")[0]
```

This could be implemented as an option. Similar to "arrayMerge", but for objects.

I do not see any simple way to implement this requirement outside of the deepmerge.

How do you think about this?

If you consider this a useful feature, then I will try to implement it as a PR.

**Comment by TehShrike** [comment]
Key/value transformations seem outside of the scope of deepmerge.  There are some other libraries that do object transformations that would be good to use - Sindre's [modify-keys](https://github.com/sindresorhus/modify-keys) looks good.

Do you need this done to all objects, or just the ones at the top level?

**Comment by jzimmek** [comment]
Will look into the modify-keys lib.

Yes, needs to be done at arbitrary depth.

**Comment by TehShrike** [comment]
I wonder if some part of this library could be published stand-alone, to make it easier to implement functions recursively on objects.  There might be value in just publishing `isMergeableObject` by itself.

It would be cool to make it trivial to take something like `modify-keys` and apply it recursively in the same way that this library traverses objects recursively.

**Comment by TehShrike** [comment]
I published `is-mergeable-object`, which means that this function will recursively alter keys in the way that you want:

```js
const isMergeableObject = require('is-mergeable-object')
const modifyKeys = require('modify-keys')

function modifyKeysRecursively(o) {
	const modified = modifyKeys(o, key => key.replace(/__\d+$/, ''))

	Object.keys(modified).filter(key => isMergeableObject(modified[key])).forEach(key => {
		modified[key] = modifyKeysRecursively(modified[key])
	})

	return modified
}
```

```js
modifyKeysRecursively({
	foo__1: {
		bar__2: 3
	},
}) // => { foo: { bar: 3 } }
```

You should be able to get your desired behavior by calling 
```js
merge(modifyKeysRecursively(x), modifyKeysRecursively(y))
```

**Comment by jzimmek** [comment]
That looks great. Thanks!
