### ISSUE TITLE
Array to Object not working as expected

### ISSUE THREAD

**Issue by alexandernanberg** [KyleAMathews/deepmerge#65]
Having some problems with converting arrays to objects and discarding current array values.

```js
const deepmerge = require('deepmerge');

const x = {
  prop: ['hello'],
}

const y = {
  prop: {
    name: 'foo',
    value: 'bar'
  }
}

const result = deepmerge(x, y);

result.prop 
// expected { name: 'foo', value: 'bar' } but resulted in { 0: 'hello', name: 'foo', value: 'bar' }  

```

Is it possible to achieve what I'm looking for?

**Comment by TehShrike** [comment]
I think you're right, this looks like a bug.

I'd be worried that somebody might be relying on this behavior, though - I would probably release it as a feature version bump at least.

Anyone have any thoughts?
