### ISSUE TITLE
merge with empty object

### ISSUE THREAD

**Issue by revati** [KyleAMathews/deepmerge#81]
Hello,i have issue with merging. I dont even know how you could help, but still.

```js
let item = {key: {innerKey: "value"}}
let item2 = {key: {}}
deepmerge(item, item2) // {key: {innerKey: "value"}}
```

is there some workaround?

**Comment by TehShrike** [comment]
What output do you expect/want?

**Comment by revati** [comment]
i would want `{key: {}}` :)

**Comment by TehShrike** [comment]
Then you don't want a recursive object merge function - `Object.assign(item, item2)` will give you what you want.

**Comment by revati** [comment]
sad, this is very oversimplified example. In reality such case can occur very deeply nested within objects. and for almost every object within tree

Probably will have to fork your library and make some silly if object is empty exception.

**Comment by TehShrike** [comment]
¯\\\_(ツ)\_/¯

That exception does seem silly.

I can't guess why someone would expect "merge objects, unless one of them has no keys" behavior.

The only way that could ever get that behavior in an object-merging library would be if the library exposed a way to supply your own custom object-merging algorithm, like how deepmerge lets you supply your own array-merging algorithm.

**Comment by revati** [comment]
yes, i understand, this indeed isn't generic merge that could be implemented in such library.
its too specific for our use case.

Thanks for quick responses :)

great library tho
