### ISSUE TITLE
oldArrayMerge() example code is non-executable

### ISSUE THREAD

**Issue by matatk** [KyleAMathews/deepmerge#83]
I'm trying to use the example `oldArrayMerge()` code [given in the README](https://github.com/KyleAMathews/deepmerge#arraymerge) but it won't run, as `cloneIfNecessary()` and `isMergeableObject()` are not defined. I see that `isMergeableObject()` can be got from another package (though it would be much neater if deepmerge could expose it as a pass-through), but `cloneIfNecessary()` doesn't seem to be defined anywhere.

My code depends on the pre-2.0.0 behaviour for array merging, so it would be really helpful to be able to reproduce this on the latest 2.0.0 code.

Thanks for this tool; it is very helpful, and I also appreciate the efforts you have gone to to explain how to keep the pre-2.0.0 behaviour; hope this issue report helps with that.

**Comment by TehShrike** [comment]
Good point.  And relatedly, there's no example code *executing* that function - if there was, then `jsmd` would have caught the error when running the automated tests.

**Comment by matatk** [comment]
I did have a quick look at your build process, noticed `jsmd` and wondered what it did—sounds very helpful, and could be of use in a few projects on which I work; thanks :-).
