### ISSUE TITLE
Breaking coming across functions as plugins, not updated to latest webpack/babel types

### ISSUE THREAD

**Issue by Kielan** [KyleAMathews/deepmerge#91]
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/681

here is an example
https://github.com/Kielan/testWebpackErr

**Comment by TehShrike** [comment]
I don't see anything that relates to deepmerge?

**Comment by Kielan** [comment]
in Webpack build to create module recipes. If plugins array is not empty and has extractTextPlugin or webpack.DefinePlugin or really any plugin object up to date with the newest webpack/babel types deepmerge triggers a webpack error. You can add this code to plugins and see for yourself

var plugins = [
  new webpack.DefinePlugin({
    'process.env': {
    }
  })

https://github.com/Kielan/testWebpackErr/blob/master/tools/webpack.client.js

**Comment by TehShrike** [comment]
So you're using deepmerge on some Webpack config objects, and the output isn't what you would expect?

Can you give an example of input to deepmerge that produces output other than what you would expect?  And also, what you're expecting?

We need these three things:

1. what to do to reproduce the issue
2. the output you expect from those reproduction steps
3. the output you're actually getting from those reproduction steps

The example reproduction steps should only involve deepmerge, they shouldn't require us to run Webpack.

**Comment by Kielan** [comment]
In the previous issue linked I covered all of these things. When including plugins, including extract-text-webpack-plugin and webpack.DefinePlugin deepmerge produces a result which breaks webpack. On webpack 3 the error is more cryptic, 
arguments[i] apply is not a function

but in webpack 4

configuration.plugins[0] should be one of these:
   object { apply, ... } | function

so webpack deepmerge on these objects loses the function output with the apply prototype option which webpack needs to use

**Comment by TehShrike** [comment]
deepmerge doesn't have anything to do with Webpack.  We're not going to debug Webpack for you.  If you're passing bad configuration to Webpack, you need to figure out what you're passing in that it doesn't like.

use `console.log(JSON.stringify(object))` to print out the two inputs that you're merging, and the output that is coming out.  If you paste those here, along with what you think the output should be, we can see if it looks like a bug in deepmerge or if you're just passing in incorrect objects.

**Comment by Kielan** [comment]
Ok this has been used in the past in some examples as a webpack object merging tool. I figure they changed the API so that a generic tool cannot be used.

**Comment by TehShrike** [comment]
As long as Webpack configurations are made up of JS data structures like objects and arrays, you can use deepmerge to combine them.

Your configuration objects are incorrect - if you make them correct, everything should work fine.

**Comment by Kielan** [comment]
they were functions that returned objects in this case

**Comment by TehShrike** [comment]
You'll have to call the functions to get the object before you can merge them.  deepmerge doesn't call functions that you pass to it.

**Comment by nedeljko-vidovic** [comment]
This is not a Webpack issue, it's a deepmerge issue. 

When merging the two following objects:

`{ entry: './src/index.ts',
  devtool: 'inline-source-map',
  output:
   { filename: 'bundle.js',
     path: 'somethingunimportant' },
  module: { rules: [ [Object], [Object], [Object], [Object] ] },
  resolve: { extensions: [ '.tsx', '.ts', '.js' ] },
  plugins:
   [ ExtractTextPlugin { filename: 'styles.css', id: 1, options: {} },
     BabelMinifyPlugin { options: [Object] },
     HtmlWebpackPlugin { options: [Object] } ] }`

`{ plugins:
   [ BabelMinifyPlugin { options: [Object] },
     DefinePlugin { definitions: [Object] } ] }`

The output is:

`{ entry: './src/index.ts',
  devtool: 'inline-source-map',
  output:
   { filename: 'bundle.js',
     path: 'somethingunimportant' },
  module: { rules: [ [Object], [Object], [Object], [Object] ] },
  resolve: { extensions: [ '.tsx', '.ts', '.js' ] },
  plugins:
   [ { filename: 'styles.css', id: 1, options: {} },
     { options: [Object] },
     { options: [Object] },
     { options: [Object] },
     { definitions: [Object] } ] }`

As you can see the type information on the `plugins` array has been lost.
This is what breaks webpack.

I'm not sure if deepmerge was intended to work with TypeScript or not, though.

**Comment by TehShrike** [comment]
This is deepmerge working as currently intended.  Objects are cloned onto new, plain objects.

If #95 was implemented, you could pass in `is-plain-object` and deepmerge would behave more like you are expecting, where "class" instantiated objects would not be cloned.

**Comment by TehShrike** [comment]
This would be fixed by #96.  Check out the documentation changes there, see if you think it looks reasonable.

**Comment by anneincoding** [comment]
@Kielan  hi, I met the same problem as yours , I use webpack4 and webpack-merge, did you solve the problem?

`WebpackOptionsValidationError: Invalid configuration object. Webpack has beeninitialised using a configuration object that does not match the API schema.
 - configuration.plugins[1] should be one of these:
   object { apply, … } | function
   -> Plugin of type object or instanceof Function
   Details:
    * configuration.plugins[1] should be an object.
      -> Plugin instance
    * configuration.plugins[1] should be an instance of function
      -> Function acting as plugin`

**Comment by DominusVilicus** [comment]
i think I am still having this issue

**Comment by davidpatters0n** [comment]
I was having the same issue, however I was able to resolve it by switching `require('deep-extend')` →  `require('webpack-merge')`

**Comment by TehShrike** [comment]
@davidpatters0n this package is not `deep-extend` or `webpack-merge`, I think you commented on the wrong repo
